version: "3.7"
services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
       MYSQL_ROOT_PASSWORD: 1234
    
  api:
    build: "./"
    container_name: api-container
    image: springboot
    restart: always
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    volumes:
      - "./teste:/home/api_rest"
    ports: 
      - "8080:8080"
    depends_on:
      - db